[package]
name = "RustyChip"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
fermium = "20016.1.1"
rand = "0.8.5"
rodio = "0.15.0"